
import __ASTRO_IMAGE_IMPORT_0 from "./flange-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_1 from "./footer-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_2 from "./get-creative.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_3 from "./radius-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_4 from "./support-style-demo.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_5 from "./texture-demo.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_6 from "./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fentry-001%2Fentry-001.md";
import __ASTRO_IMAGE_IMPORT_7 from "./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_8 from "./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_9 from "./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fpremier-rides-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_10 from "./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fpremier-rides-track-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_11 from "./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Futility-nodes%2F_content.md";
import __ASTRO_IMAGE_IMPORT_12 from "./track-connector-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_13 from "./track-demo-01.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_14 from "./track-demo-02.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md";
import __ASTRO_IMAGE_IMPORT_15 from "thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fentry-001%2Fentry-001.md";
export default new Map([["./flange-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_0], ["./footer-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_1], ["./get-creative.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_2], ["./radius-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_3], ["./support-style-demo.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_4], ["./texture-demo.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_5], ["./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fentry-001%2Fentry-001.md", __ASTRO_IMAGE_IMPORT_6], ["./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_7], ["./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_8], ["./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fpremier-rides-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_9], ["./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fpremier-rides-track-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_10], ["./thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Futility-nodes%2F_content.md", __ASTRO_IMAGE_IMPORT_11], ["./track-connector-demo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-support-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_12], ["./track-demo-01.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_13], ["./track-demo-02.gif?astroContentImageFlag=&importer=src%2Fcontent%2Ftools%2Fb%26m-track-generator%2F_content.md", __ASTRO_IMAGE_IMPORT_14], ["thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fentry-001%2Fentry-001.md", __ASTRO_IMAGE_IMPORT_15]]);
		