services:
    directus:
        image: directus/directus:12.0.2
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "AXOMg#l>ji8|fJv%hIq@Y1R;_42zFpbDiB{;mu!>;E>C})nYu48dk]@{OQY!tJHR"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
            PUBLIC_URL: "http://localhost:8055/"
            LICENSE_KEY: ""
            EXTENSIONS_AUTO_RELOAD: true
